.TH "ABenchmark" 3 "Sun Dec 27 2020" "openPilotLog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ABenchmark \- The \fBABenchmark\fP class provides quick access to benchmarking two functions for the purpose of performance testing\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <abenchmark\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBABenchmark\fP (void(*function_one)(), void(*function_two)(), int number_of_runs)"
.br
.ti -1c
.RI "\fBABenchmark\fP (bool(*function_one)(), bool(*function_two)(), int number_of_runs)"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBABenchmark\fP class provides quick access to benchmarking two functions for the purpose of performance testing\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for openPilotLog from the source code\&.
