.TH "DatabaseError" 3 "Fri Mar 4 2022" "openPilotLog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DatabaseError \- Custom Database Error derived from QSqlError\&. Extends text() adding 'Database Error: ' before the text\&. Errors that are related to SQL are assigned their respective error codes\&. Errors that occur with data in the database are handled with the error code 'opl' and QSqlError::UnknownError\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <database\&.h>\fP
.PP
Inherits QSqlError\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDatabaseError\fP (QString msg)"
.br
.ti -1c
.RI "QString \fBtext\fP () const"
.br
.ti -1c
.RI "\fBDatabaseError\fP (QSqlError)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Custom Database Error derived from QSqlError\&. Extends text() adding 'Database Error: ' before the text\&. Errors that are related to SQL are assigned their respective error codes\&. Errors that occur with data in the database are handled with the error code 'opl' and QSqlError::UnknownError\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for openPilotLog from the source code\&.
