.TH "Aircraft" 3 "Sat Dec 26 2020" "openPilotLog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Aircraft \- The aircraft class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <aircraft\&.h>\fP
.PP
Inherits \fBEntry_deprecated\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAircraft\fP (int tail_id)"
.br
.ti -1c
.RI "\fBAircraft\fP (QMap< QString, QString > newData)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The aircraft class\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for openPilotLog from the source code\&.
