.TH "APilotEntry" 3 "Sat May 1 2021" "openPilotLog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
APilotEntry
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAEntry\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAPilotEntry\fP (RowId_T row_id)"
.br
.ti -1c
.RI "\fBAPilotEntry\fP (RowData_T table_data)"
.br
.ti -1c
.RI "\fBAPilotEntry\fP (const \fBAPilotEntry\fP &pe)=default"
.br
.ti -1c
.RI "\fBAPilotEntry\fP & \fBoperator=\fP (const \fBAPilotEntry\fP &pe)=default"
.br
.ti -1c
.RI "const QString \fBname\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for openPilotLog from the source code\&.
