.TH "ARunGuard" 3 "Fri Mar 4 2022" "openPilotLog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ARunGuard \- The RunGuard class ensures only a single instance of the application is running simultaneously\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <arunguard\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBARunGuard\fP (const QString &key)"
.br
.ti -1c
.RI "bool \fBisAnotherRunning\fP ()"
.br
.ti -1c
.RI "bool \fBtryToRun\fP ()"
.br
.ti -1c
.RI "void \fBrelease\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
The RunGuard class ensures only a single instance of the application is running simultaneously\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for openPilotLog from the source code\&.
