.TH "ASettings" 3 "Sat Dec 26 2020" "openPilotLog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ASettings \- The Settings class is a thin wrapper for the QSettings class, simplifying reading and writing of settings\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <asettings\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static QVariant \fBread\fP (const QString &key)"
.br
.ti -1c
.RI "static void \fBwrite\fP (const QString &key, const QVariant &val)"
.br
.in -1c
.SH "Detailed Description"
.PP 
The Settings class is a thin wrapper for the QSettings class, simplifying reading and writing of settings\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for openPilotLog from the source code\&.
