.TH "ATailEntry" 3 "Tue May 4 2021" "openPilotLog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ATailEntry
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAEntry\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBATailEntry\fP (const \fBATailEntry\fP &te)=default"
.br
.ti -1c
.RI "\fBATailEntry\fP & \fBoperator=\fP (const \fBATailEntry\fP &te)=default"
.br
.ti -1c
.RI "\fBATailEntry\fP (RowId_T row_id)"
.br
.ti -1c
.RI "\fBATailEntry\fP (RowData_T table_data)"
.br
.ti -1c
.RI "const QString \fBregistration\fP ()"
.br
.ti -1c
.RI "const QString \fBtype\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for openPilotLog from the source code\&.
