.TH "BackupWidget" 3 "Fri Apr 30 2021" "openPilotLog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BackupWidget
.SH SYNOPSIS
.br
.PP
.PP
Inherits QWidget\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBackupWidget\fP (QWidget *parent=nullptr)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for openPilotLog from the source code\&.
