.TH "DataPosition" 3 "Sun May 2 2021" "openPilotLog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DataPosition
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDataPosition\fP (TableName_T table_name, RowId_T row_id)"
.br
.ti -1c
.RI "\fBDataPosition\fP (const \fBDataPosition\fP &other)=default"
.br
.ti -1c
.RI "\fBDataPosition\fP & \fBoperator=\fP (const \fBDataPosition\fP &other)=default"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "TableName_T \fBtableName\fP"
.br
.ti -1c
.RI "RowId_T \fBrowId\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for openPilotLog from the source code\&.
