.TH "DebugWidget" 3 "Tue May 4 2021" "openPilotLog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DebugWidget
.SH SYNOPSIS
.br
.PP
.PP
Inherits QWidget\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDebugWidget\fP (QWidget *parent=nullptr)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBchangeEvent\fP (QEvent *event) override"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for openPilotLog from the source code\&.
