.TH "experimental::DatabaseError" 3 "Sun Dec 27 2020" "openPilotLog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
experimental::DatabaseError \- Custom Database Error derived from QSqlError\&. Extends text() adding 'Database Error: ' before the text\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <database\&.h>\fP
.PP
Inherits QSqlError\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDatabaseError\fP (QString msg)"
.br
.ti -1c
.RI "QString \fBtext\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Custom Database Error derived from QSqlError\&. Extends text() adding 'Database Error: ' before the text\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for openPilotLog from the source code\&.
