.TH "experimental::DataPosition" 3 "Sun Dec 27 2020" "openPilotLog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
experimental::DataPosition
.SH SYNOPSIS
.br
.PP
.PP
Inherits QPair< TableName, RowId >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDataPosition\fP (TableName table_name, RowId row_id)"
.br
.ti -1c
.RI "\fBDataPosition\fP (const \fBDataPosition\fP &other)=default"
.br
.ti -1c
.RI "\fBDataPosition\fP & \fBoperator=\fP (const \fBDataPosition\fP &other)=default"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "TableName \fBtableName\fP"
.br
.ti -1c
.RI "RowId \fBrowId\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for openPilotLog from the source code\&.
