.TH "Flight" 3 "Sat Dec 26 2020" "openPilotLog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Flight
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEntry_deprecated\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFlight\fP (int flight_id)"
.br
.ti -1c
.RI "\fBFlight\fP (QMap< QString, QString > newData)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for openPilotLog from the source code\&.
