.TH "HomeWidget" 3 "Fri Apr 30 2021" "openPilotLog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HomeWidget
.SH SYNOPSIS
.br
.PP
.PP
Inherits QWidget\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBrefresh\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHomeWidget\fP (QWidget *parent=nullptr)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for openPilotLog from the source code\&.
