.TH "LogbookWidget" 3 "Fri Apr 30 2021" "openPilotLog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LogbookWidget
.SH SYNOPSIS
.br
.PP
.PP
Inherits QWidget\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBrefresh\fP ()"
.br
.ti -1c
.RI "void \fBonLogbookWidget_viewSelectionChanged\fP (\fBSettingsWidget::SettingSignal\fP signal)"
.br
.ti -1c
.RI "void \fBrepopulateModel\fP ()"
.br
.RI "\fBLogbookWidget::repopulateModel\fP (public slot) - re-populates the model to cater for a change to the database connection (for example, when a backup is created) "
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLogbookWidget\fP (QWidget *parent=nullptr)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for openPilotLog from the source code\&.
