.TH "md__r_e_a_d_m_e" 3 "Sat May 1 2021" "openPilotLog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__r_e_a_d_m_e \- openPilotLog 
Welcome to openPilotLog, the free and open source airline pilot logbook application!
.SH "Tl;dr"
.PP
Airline pilots are required to maintain a logbook containing details of their flights\&. These logbooks were historically written by hand on paper, but of course nowadays more and more people are doing it electronically, be it in their own excel sheet or using a paid logbook software\&.
.PP
I have used paid solutions for many years, and have seen more and of them move from being a one-time license purchase to becoming a 'Logbook as a Service' type subscription\&. After the one I have been using for the last couple of years, and had bought a 'lifetime license' for ended up announcing they also moved to a subscription based service, I decided that it is time for a free and open source alternative that is fast, easy to use, and does not require a subscription\&.
.SH "The state of the project!"
.PP
openPilotLog is currently in development, so no release is provided yet\&. If you would like to be informed about upcoming releases, you can \fCsubscribe\fP to our newsletter\&.
.PP
If you want to learn more about this project, check out the \fCwiki\fP or the \fCblog\fP!
.PP
For developers, the code documentation can be found at our \fCdoxygen\fP pages\&. If you are interested in contributing to the project, you can get in touch \fChere\fP\&.
.SH "How does it look like?"
.PP
Here are some early screenshots:
.PP
.PP
.PP
.PP
 
