.TH "NewPilotDialog" 3 "Tue May 4 2021" "openPilotLog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NewPilotDialog
.SH SYNOPSIS
.br
.PP
.PP
Inherits QDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNewPilotDialog\fP (QWidget *parent=nullptr)"
.br
.ti -1c
.RI "\fBNewPilotDialog\fP (int rowId, QWidget *parent=nullptr)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for openPilotLog from the source code\&.
