.TH "NewTailDialog" 3 "Sun May 2 2021" "openPilotLog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NewTailDialog \- The NewTail class is a dialog for adding a new tail to the database or editing an existing one\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <newtaildialog\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNewTailDialog\fP (QString new_registration, QWidget *parent=nullptr)"
.br
.ti -1c
.RI "\fBNewTailDialog\fP (int row_id, QWidget *parent=nullptr)"
.br
.in -1c
.SH "Detailed Description"
.PP 
The NewTail class is a dialog for adding a new tail to the database or editing an existing one\&. 

For a new tail, construct using QString reg\&. For editing an existing tail, provide the aircraft object\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for openPilotLog from the source code\&.
