.TH "OPL::ANotificationHandler" 3 "Mon Jul 11 2022" "openPilotLog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OPL::ANotificationHandler \- The \fBANotificationHandler\fP class handles displaying of user-directed messages\&. It displays information to the user in a QMessageBox and forwards the displayed message to \fBALog\fP so it is written to the console and log files\&. The INFO, WARN and CRIT makros provide convenient access\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <opl\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBinfo\fP (const QString msg, QWidget *parent=nullptr)"
.br
.ti -1c
.RI "static void \fBwarn\fP (const QString msg, QWidget *parent=nullptr)"
.br
.ti -1c
.RI "static void \fBcrit\fP (const QString msg, QWidget *parent=nullptr)"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBANotificationHandler\fP class handles displaying of user-directed messages\&. It displays information to the user in a QMessageBox and forwards the displayed message to \fBALog\fP so it is written to the console and log files\&. The INFO, WARN and CRIT makros provide convenient access\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for openPilotLog from the source code\&.
