.TH "OPL::AirportEntry" 3 "Tue Aug 9 2022" "openPilotLog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OPL::AirportEntry \- A \fBRow\fP representing an Airport entry\&. See \fBRow\fP class for details\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <row\&.h>\fP
.PP
Inherits \fBOPL::Row\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAirportEntry\fP (const RowData_T &row_data)"
.br
.ti -1c
.RI "\fBAirportEntry\fP (int row_id, const RowData_T &row_data)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A \fBRow\fP representing an Airport entry\&. See \fBRow\fP class for details\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for openPilotLog from the source code\&.
