.TH "OPL::PilotEntry" 3 "Mon Jul 11 2022" "openPilotLog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OPL::PilotEntry
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBOPL::Row\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPilotEntry\fP (const RowData_T &row_data)"
.br
.ti -1c
.RI "\fBPilotEntry\fP (int row_id, const RowData_T &row_data)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for openPilotLog from the source code\&.
