.TH "Pilot" 3 "Sun Dec 27 2020" "openPilotLog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Pilot
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEntry_deprecated\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPilot\fP (int pilot_id)"
.br
.ti -1c
.RI "\fBPilot\fP (QMap< QString, QString > newData)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for openPilotLog from the source code\&.
