.TH "ProcessPilots" 3 "Fri Mar 4 2022" "openPilotLog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProcessPilots
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProcessPilots\fP (const QVector< QStringList > &raw_csv_data)"
.br
.ti -1c
.RI "void \fBinit\fP ()"
.br
.ti -1c
.RI "QHash< QString, QHash< QString, QVariant > > \fBgetProcessedPilotMaps\fP () const"
.br
.ti -1c
.RI "QHash< QString, int > \fBgetProcessedPilotsIds\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for openPilotLog from the source code\&.
