.TH "ProcessFlights" 3 "Mon Jul 11 2022" "openPilotLog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProcessFlights
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProcessFlights\fP (const QVector< QStringList > &raw_csv_data, const QHash< QString, int > &processed_pilots_ids, const QHash< QString, int > &processed_tails_ids)"
.br
.ti -1c
.RI "void \fBinit\fP ()"
.br
.ti -1c
.RI "QVector< QHash< QString, QVariant > > \fBgetProcessedFlights\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for openPilotLog from the source code\&.
