.TH "ProcessAircraft" 3 "Fri Mar 4 2022" "openPilotLog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProcessAircraft
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProcessAircraft\fP (const QVector< QStringList > &raw_csv_data)"
.br
.ti -1c
.RI "void \fBinit\fP ()"
.br
.ti -1c
.RI "QMap< QString, QMap< QString, QVariant > > \fBgetProcessedTailMaps\fP () const"
.br
.ti -1c
.RI "QMap< QString, int > \fBgetProcessedTailIds\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for openPilotLog from the source code\&.
