.TH "SettingsWidget" 3 "Sat May 1 2021" "openPilotLog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SettingsWidget
.SH SYNOPSIS
.br
.PP
.PP
Inherits QWidget\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBSettingSignal\fP { \fBLogbookWidget\fP, \fBHomeWidget\fP, \fBAircraftWidget\fP, \fBPilotsWidget\fP }"
.br
.RI "Widgets that need to receive a signal when a setting is updated\&. "
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBsettingChanged\fP (\fBSettingSignal\fP widget)"
.br
.RI "settingChanged is emitted when a setting change shall trigger an update to another widget\&. "
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSettingsWidget\fP (QWidget *parent=nullptr)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for openPilotLog from the source code\&.
