.TH "todo" 3 "Sun Dec 27 2020" "openPilotLog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 

.IP "\fBNamespace \fBexperimental\fP \fP" 1c
Remove this namespace (and learn about some nice \\something of doxygen) Decide documentation style\&. https://www.doxygen.nl/manual/docblocks.html#specialblock  
.IP "\fBClass \fBexperimental::UserInput\fP \fP" 1c
Figure out exactly what the database would prefer as return value George: I would assume key: value pairs where the keys are what you would put in the queries\&. This will affect data aswell (and propably simplify it) 
.PP

