.TH "todo" 3 "Tue May 4 2021" "openPilotLog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 

.IP "\fBMember \fBADatabase::getIdMap\fP (ADatabaseTarget target)\fP" 1c
What is this QString semantically? As i understand its a 'QueryResult' QVariant cast to QString  
.IP "\fB" \fP" 1c
Short descriptions 
.PP

