.TH "todo" 3 "Sat May 1 2021" "openPilotLog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 

.IP "\fBMember \fBADatabase::getIdMap\fP (ADatabaseTarget target)\fP" 1c
What is this QString semantically? As i understand its a 'QueryResult' QVariant cast to QString  
.IP "\fBMember \fBADatabase::databaseSummary\fP (const QString &db_path)\fP" 1c
Contemplate whether it should be a more generic function that may be used for different elements to summarize\&. and ADD DOCUMENTATION, theres some specific sql stuff going on\&.  
.IP "\fB" \fP" 1c
Short descriptions 
.PP

