.TH "ValidationState" 3 "Tue Aug 9 2022" "openPilotLog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ValidationState \- The \fBValidationState\fP class encapsulates a QBitArray that has a bit set (or unset) depending on wether the input for the associated index has been verified\&. The indexes correspond to the mandatory items enumerated in the ValidationItem enum\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <newflightdialog\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBValidationItem\fP { \fBdoft\fP = 0, \fBdept\fP = 1, \fBdest\fP = 2, \fBtofb\fP = 3, \fBtonb\fP = 4, \fBpic\fP = 5, \fBacft\fP = 6 }"
.br
.RI "The ValidationItem enum contains the items that are mandatory for logging a flight: Date of Flight, Departure, Destination, Time Off Blocks, Time On Blocks, Pilot in Command, Aircraft Registration\&. "
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBvalidate\fP (\fBValidationItem\fP item)"
.br
.ti -1c
.RI "void \fBvalidate\fP (int index)"
.br
.ti -1c
.RI "void \fBinvalidate\fP (\fBValidationItem\fP item)"
.br
.ti -1c
.RI "void \fBinvalidate\fP (int index)"
.br
.ti -1c
.RI "bool \fBallValid\fP () const"
.br
.ti -1c
.RI "bool \fBtimesValid\fP () const"
.br
.ti -1c
.RI "bool \fBlocationsValid\fP () const"
.br
.ti -1c
.RI "bool \fBnightDataValid\fP () const"
.br
.ti -1c
.RI "bool \fBacftValid\fP () const"
.br
.ti -1c
.RI "bool \fBvalidAt\fP (int index) const"
.br
.ti -1c
.RI "bool \fBvalidAt\fP (\fBValidationItem\fP item) const"
.br
.ti -1c
.RI "void \fBprintValidationStatus\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBValidationState\fP class encapsulates a QBitArray that has a bit set (or unset) depending on wether the input for the associated index has been verified\&. The indexes correspond to the mandatory items enumerated in the ValidationItem enum\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for openPilotLog from the source code\&.
